spring.application.name=stockx-api
spring.datasource.url=jdbc:postgresql://localhost:5432/stockx
spring.datasource.username=postgres
spring.datasource.password=bharti
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9000